-- MySQL Script generated by MySQL Workbench
-- 02/14/16 22:12:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema restaurantdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restaurantdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurantdb` DEFAULT CHARACTER SET utf8 ;
USE `restaurantdb` ;

-- -----------------------------------------------------
-- Table `restaurantdb`.`restaurants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurantdb`.`restaurants` (
  `restaurantId` INT NOT NULL AUTO_INCREMENT,
  `restaurantName` VARCHAR(100) NOT NULL,
  `scheduleIsReady` INT NULL,
  PRIMARY KEY (`restaurantId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurantdb`.`jobCycle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurantdb`.`jobCycle` (
  `cycleId` INT NOT NULL AUTO_INCREMENT,
  `workdays` INT NOT NULL,
  `daysoff` INT NOT NULL,
  `cyclename` VARCHAR(45) NULL,
  PRIMARY KEY (`cycleId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurantdb`.`chefs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurantdb`.`chefs` (
  `chefId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `patronymic` VARCHAR(45) NULL,
  `hasJapSkills` INT NULL,
  `hasItaSkills` INT NULL,
  `hasRusSkills` INT NULL,
  `daysBeginTime` TIME NOT NULL,
  `daysEndTime` TIME NOT NULL,
  `offsetSchedule` INT NULL,
  `jobCycle_id` INT NOT NULL,
  `restaurants_id` INT NOT NULL,
  PRIMARY KEY (`chefId`, `jobCycle_id`, `restaurants_id`),
  INDEX `fk_chefs_jobCycle1_idx` (`jobCycle_id` ASC),
  INDEX `fk_chefs_restaurants1_idx` (`restaurants_id` ASC),
  CONSTRAINT `fk_chefs_jobCycle1`
    FOREIGN KEY (`jobCycle_id`)
    REFERENCES `restaurantdb`.`jobCycle` (`cycleId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chefs_restaurants1`
    FOREIGN KEY (`restaurants_id`)
    REFERENCES `restaurantdb`.`restaurants` (`restaurantId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
